### PR TITLE
Improve the documentation for building the container

### PR DESCRIPTION
**Pull request by NicolasCARPi**
* Add build steps
* Add --rm flag so stopped containers are destroyed
* Add --name flag
* Add bash syntax highlighting

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Hello?

**Comment by NicolasCARPi** [comment]
Is nobody watching this repository? @xispa ?

**Review by ramonski — CHANGES_REQUESTED** [review]
Thanks for your PR @NicolasCARPi.

Sorry for the late reply, we were indeed not watching the Repo and missed therefore the notification...

Would you kindly change the GitHub URL from `https://github.com/deltablot/senaite.docker` -> `https://github.com/senaite/senaite.docker`?

**Comment by NicolasCARPi** [comment]
Oops yes of course, it's a mistake. It has been changed :)

Regards,
~Nicolas

**Comment by ramonski** [comment]
Thanks!

**Pull request merged**
